version: '3'
services:
  web:
    build: .
    volumes:
      - ./web:/var/www/html
    ports:
      - 8081:8081
      #- 3000:3000
      - 9003:9003
    extra_hosts:
      - "host.docker.internal:172.101.0.1"

  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5434:5432

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.101.0.0/16